#!/bin/bash
set +h

print_error() {
	echo -e "ERROR: $@"
}

if [ $(id -u) != 0 ]; then
	print_error "$0 script need to run as root!"
	exit 1
fi

LFS="/mnt/lfs"
PORT=""
COMMAND="install -c --no-confirm"

while [[ "$1" != "" ]]; do
    case $1 in
		-d|--deplist)
			COMMAND="deplist"
		;;
		*)
			PORT="${PORT}${1} "
		;;
    esac
    shift
done

if [ -z "$PORT" ]; then
	PORT="core"
fi

interrupted() {
	die "script $(basename $0) aborted!"
}

die() {
	[ "$@" ] && print_error $@
	exit 1
}

trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM

CURDIR=$(cd "$(dirname $0)" && pwd)

sh $CURDIR/chroot "scratch sync" || die

sh $CURDIR/chroot "scratch $COMMAND $PORT" || die

exit 0
